target:	hw6

hw6:	gtuiterator.cpp gtuiteratorconst.cpp iterable.cpp gtuarray.cpp gtuvector.cpp gtuset.cpp main.cpp 
		g++ -std=c++11 gtuiterator.cpp gtuiteratorconst.cpp iterable.cpp gtuarray.cpp gtuvector.cpp gtuset.cpp main.cpp -lm -o hw6

clean:
		rm hw6
